/* Script-VM command handler: pull this command's operands out of the descriptor
 * array through the VM's typed fetchers, build a parameter block on the stack,
 * hand it to the overlay's builder, and post the result to
 * Ov002_SetModuleSlot. Always reports success.
 *
 * Generated by tools/gen_vm_emit.py, which reads the shape straight off the
 * disassembly -- 19 functions share this skeleton and differ only in which
 * fetcher serves each slot, the descriptor offsets, and whether a slot is a word
 * or a byte.
 *
 * Two things the generator had to get right, both of which cost bytes when
 * wrong:
 *   - `adds r4, #N` advances the descriptor BASE and it STAYS advanced, so the
 *     last fetch reads descs+N, not descs.
 *   - the builder's entry count is kept as a full word and truncated AT THE USE. Declaring
 *     it `unsigned short` truncates at the assignment instead and reorders two
 *     instructions on every member that fetches the count early.
 */

#include "game/engine.h"

typedef struct {
    int nField00;            /* +0x00 */
    int nField04;            /* +0x04 */
} Ov021EmitParams;          /* 0x8 */

extern int Ov021_CreateEmblemClass(int nCount, Ov021EmitParams *params);
extern void Ov002_SetModuleSlot(int target, int value);

int Ov021_VmCmd0e30(void *self, char *descs) {
    Ov021EmitParams params;
    int target;
    int nCount;

    target = ScriptVm_ReadOperandInt(self, descs);
    nCount = ScriptVm_ReadOperandInt(self, descs + 0x8);
    params.nField00 = ByteCode_ResolveOperand(self, descs + 0x10);
    params.nField04 = ByteCode_ResolveOperand(self, descs + 0x18);
    Ov002_SetModuleSlot(target, Ov021_CreateEmblemClass((unsigned short)nCount, &params));
    return 1;
}
