/* Ov200_AiDispatchAction -- ov200's move dispatcher. The plain family shape: -1 at ctx[0]+0x1c7 means
 * nothing queued, the id is copied to +0x1c6 and it is that copy the switch reads, and the slot is
 * cleared on every path.
 *
 * Source case order: 0, 1, 2, 8, 3, 4, 5, 6, 7, 9.
 * That is the body order, and it is what the switch has to say.
 *
 * Generated by tools/genmove.py from the machine code and verified byte-exact. */

typedef struct {
    unsigned short lo : 8;
    unsigned short hi : 8;
} Hw60;

typedef struct {
    unsigned f : 8;
} B8;

extern void SetIndexedSlot(int self, int slot, void (*cb)(void));
extern void Ov200_stateSetFlagsClearBit(void);
extern void Ov200_SpawnEffect48ReconfigureFlagsB(void);
extern void Ov200_AiEnterHover(void);
extern void Ov200_FireAimPoseAndGate(void);
extern void Ov200_SpawnEffect4bReconfigureFlags(void);
extern void Ov200_SetPoseThenAdvanceSlot(void);
extern void Ov200_SeedRandomStrafeSign(void);
extern void Ov200_AiEnterSwing(void);
extern void Ov200_EnterAttackState(void);
extern void Ov200_SpawnEffectSetFlags(void);

void Ov200_AiDispatchAction(int self) {
    int *ctx;
    unsigned short v;

    ctx = *(int **)(self + 4);
    if (*(signed char *)(ctx[0] + 0x1c7) != -1) {
        *(signed char *)(ctx[0] + 0x1c6) = *(signed char *)(ctx[0] + 0x1c7);
        v = *(unsigned short *)(ctx[0] + 0x60);
        *(unsigned short *)(ctx[0] + 0x60) =
            (unsigned short)((v & ~0xff00)
                             | (((((unsigned int)v << 0x10) >> 0x18 | 0x40) << 0x18) >> 0x10));
        ((Hw60 *)(ctx[0] + 0x60))->hi &= ~0x86;
        *(unsigned short *)(ctx[0] + 0x1ae) &= ~9;
        ((B8 *)(*(int *)(ctx[0] + 0x388) + 8))->f |= 1;

        switch (*(signed char *)(ctx[0] + 0x1c6)) {
        case 0:
            SetIndexedSlot(self, 1, Ov200_stateSetFlagsClearBit);
            break;
        case 1:
            SetIndexedSlot(self, 1, Ov200_SpawnEffect48ReconfigureFlagsB);
            break;
        case 2:
            SetIndexedSlot(self, 1, Ov200_AiEnterHover);
            break;
        case 8:
            SetIndexedSlot(self, 1, Ov200_FireAimPoseAndGate);
            break;
        case 3:
            SetIndexedSlot(self, 1, Ov200_SpawnEffect4bReconfigureFlags);
            break;
        case 4:
            SetIndexedSlot(self, 1, Ov200_SetPoseThenAdvanceSlot);
            break;
        case 5:
            SetIndexedSlot(self, 1, Ov200_SeedRandomStrafeSign);
            break;
        case 6:
            SetIndexedSlot(self, 1, Ov200_AiEnterSwing);
            break;
        case 7:
            SetIndexedSlot(self, 1, Ov200_EnterAttackState);
            break;
        case 9:
            SetIndexedSlot(self, 1, Ov200_SpawnEffectSetFlags);
            break;
        }
    }

    *(signed char *)(ctx[0] + 0x1c7) = -1;
}
