/* Script-VM command handler: pull this command's operands out of the descriptor
 * array through the VM's typed fetchers, build a parameter block on the stack,
 * hand it to the overlay's builder, and post the result to
 * Ov002_SetModuleSlot. Always reports success.
 *
 * Generated by tools/gen_vm_emit.py, which reads the shape straight off the
 * disassembly -- 19 functions share this skeleton and differ only in which
 * fetcher serves each slot, the descriptor offsets, and whether a slot is a word
 * or a byte.
 *
 * Two things the generator had to get right, both of which cost bytes when
 * wrong:
 *   - `adds r4, #N` advances the descriptor BASE and it STAYS advanced, so the
 *     last fetch reads descs+N, not descs.
 *   - the builder's entry count is kept as a full word and truncated AT THE USE. Declaring
 *     it `unsigned short` truncates at the assignment instead and reorders two
 *     instructions on every member that fetches the count early.
 */
typedef struct {
    int nField00;            /* +0x00 */
    int nField04;            /* +0x04 */
    int nField08;            /* +0x08 */
    unsigned char bField0c;   /* +0x0c */
    char pad0d[3];
    int nField10;            /* +0x10 */
    int nField14;            /* +0x14 */
    int nField18;            /* +0x18 */
    unsigned char bField1c;   /* +0x1c */
    char pad1d[3];
} Ov015EmitParams;          /* 0x20 */

extern int ByteCode_ResolveOperand(void *self, void *desc);
extern int ScriptVm_ReadOperandInt(void *self, void *desc);
extern int ScriptVm_ReadOperandFx32(void *self, void *desc);
extern int Ov015_CreateChestClass(int nCount, Ov015EmitParams *params);
extern void Ov002_SetModuleSlot(int target, int value);

int Ov015_VmCmd27a0(void *self, char *descs) {
    Ov015EmitParams params;
    int target;
    int nCount;

    target = ScriptVm_ReadOperandInt(self, descs);
    nCount = ScriptVm_ReadOperandInt(self, descs + 0x8);
    params.nField00 = ByteCode_ResolveOperand(self, descs + 0x10);
    params.nField04 = ByteCode_ResolveOperand(self, descs + 0x18);
    params.nField08 = ScriptVm_ReadOperandFx32(self, descs + 0x20);
    params.bField0c = ScriptVm_ReadOperandInt(self, descs + 0x28);
    params.nField10 = ScriptVm_ReadOperandFx32(self, descs + 0x30);
    params.nField14 = ScriptVm_ReadOperandFx32(self, descs + 0x38);
    params.nField18 = ScriptVm_ReadOperandFx32(self, descs + 0x40);
    params.bField1c = ScriptVm_ReadOperandInt(self, descs + 0x48);
    Ov002_SetModuleSlot(target, Ov015_CreateChestClass((unsigned short)nCount, &params));
    return 1;
}
