/* Ov244_AiDispatchAction -- ov244's move dispatcher. The plain family shape: -1 at ctx[0]+0x1c7 means
 * nothing queued, the id is copied to +0x1c6 and it is that copy the switch reads, and the slot is
 * cleared on every path.
 *
 * Source case order: 0, 1, 2, 4, 5, 6, 7, 3.
 * That is the body order, and it is what the switch has to say.
 *
 * Generated by tools/genmove.py from the machine code and verified byte-exact. */

typedef struct {
    unsigned short lo : 8;
    unsigned short hi : 8;
} Hw60;

typedef struct {
    unsigned f : 8;
} B8;

extern void SetIndexedSlot(int self, int slot, void (*cb)(void));
extern void Ov244_ReleaseLeap(void);
extern void Ov244_AiStep_QueueAction2(void);
extern void Ov244_AiEnterPlay(void);
extern void Ov244_HurtHook(void);
extern void Ov244_EnterAnim4(void);
extern void Ov244_EnterAnim7(void);
extern void Ov244_AiEnterCharge(void);
extern void Ov244_AiStep_SetFlags3AndEnd(void);

void Ov244_AiDispatchAction(int self) {
    int *ctx;

    ctx = *(int **)(self + 4);
    if (*(signed char *)(ctx[0] + 0x1c7) != -1) {
        *(unsigned short *)(ctx[0] + 0x1ae) &= ~1;
        ((B8 *)(*(int *)(ctx[0] + 0x39c) + 8))->f |= 1;
        ((B8 *)(*(int *)(ctx[0] + 0x3a0) + 8))->f |= 1;
        ((B8 *)(*(int *)(ctx[0] + 0x3a4) + 8))->f |= 1;
        ((Hw60 *)(ctx[0] + 0x60))->hi &= ~0x8e;
        *(signed char *)(ctx[0] + 0x1c6) = *(signed char *)(ctx[0] + 0x1c7);

        switch (*(signed char *)(ctx[0] + 0x1c6)) {
        case 0:
            SetIndexedSlot(self, 1, Ov244_ReleaseLeap);
            break;
        case 1:
            SetIndexedSlot(self, 1, Ov244_AiStep_QueueAction2);
            break;
        case 2:
            SetIndexedSlot(self, 1, Ov244_AiEnterPlay);
            break;
        case 4:
            SetIndexedSlot(self, 1, Ov244_HurtHook);
            break;
        case 5:
            SetIndexedSlot(self, 1, Ov244_EnterAnim4);
            break;
        case 6:
            SetIndexedSlot(self, 1, Ov244_EnterAnim7);
            break;
        case 7:
            SetIndexedSlot(self, 1, Ov244_AiEnterCharge);
            break;
        case 3:
            SetIndexedSlot(self, 1, Ov244_AiStep_SetFlags3AndEnd);
            break;
        }
    }

    *(signed char *)(ctx[0] + 0x1c7) = -1;
}
