/* Script-VM command handler (family skeleton + the three ordering rules:
 * tools/gen_vm_emit.py). Generated by that tool and verified byte-exact.
 *
 * This one is in the group that only started matching once the generator learned
 * that `strh` is a HALFWORD. It had been treating everything that was not `strb`
 * as a word, so any parameter block with 16-bit slots came out with the wrong
 * field widths and every field after them shifted -- five members of the family
 * were blocked by that single assumption.
 */
typedef struct {
    int nField00;            /* +0x00 */
    int nField04;            /* +0x04 */
    int nField08;            /* +0x08 */
    int nField0c;            /* +0x0c */
    unsigned char bField10;   /* +0x10 */
    char pad11[1];
    short nField12;          /* +0x12 */
    short nField14;          /* +0x14 */
    short nField16;          /* +0x16 */
} Ov017EmitParams;          /* 0x18 */

extern int ByteCode_ResolveOperand(void *self, void *desc);
extern int ScriptVm_ReadOperandInt(void *self, void *desc);
extern int ScriptVm_ReadOperandFx32(void *self, void *desc);
extern int Ov017_CreateDepositClass(unsigned short id, Ov017EmitParams *params);
extern void Ov002_SetModuleSlot(int target, int value);

int Ov017_MarshalAndDispatch(void *self, char *descs) {
    Ov017EmitParams params;
    int target;
    int id;

    target = ScriptVm_ReadOperandInt(self, descs);
    id = ScriptVm_ReadOperandInt(self, descs + 0x8);
    params.nField00 = ByteCode_ResolveOperand(self, descs + 0x10);
    params.nField04 = ByteCode_ResolveOperand(self, descs + 0x18);
    params.nField08 = ByteCode_ResolveOperand(self, descs + 0x20);
    params.nField0c = ScriptVm_ReadOperandFx32(self, descs + 0x28);
    params.bField10 = ScriptVm_ReadOperandInt(self, descs + 0x30);
    params.nField12 = ScriptVm_ReadOperandFx32(self, descs + 0x38);
    params.nField14 = ScriptVm_ReadOperandFx32(self, descs + 0x40);
    params.nField16 = ScriptVm_ReadOperandFx32(self, descs + 0x48);
    Ov002_SetModuleSlot(target, Ov017_CreateDepositClass((unsigned short)id, &params));
    return 1;
}
