/* Ov245_Carrier_AiDispatchAction -- ov245's move dispatcher. The plain family shape: -1 at ctx[0]+0x1c7 means
 * nothing queued, the id is copied to +0x1c6 and it is that copy the switch reads, and the slot is
 * cleared on every path.
 *
 * The "nothing queued" case RETURNS outright (a predicated `popeq`).
 *
 * Source case order: 0, 1, 2, 4, 5, 3.
 * That is the body order, and it is what the switch has to say.
 *
 * Generated by tools/genmove.py from the machine code and verified byte-exact. */

typedef struct {
    unsigned short lo : 8;
    unsigned short hi : 8;
} Hw60;

typedef struct {
    unsigned f : 8;
} B8;

extern void SetIndexedSlot(int self, int slot, void (*cb)(void));
extern void Ov245_stateSetFlagsClearBit_2(void);
extern void Ov245_StunTick(void);
extern void Ov245_StartHoverWait(void);
extern void Ov245_Carrier_AiEnterCharge(void);
extern void Ov245_SetPose3ThenAdvanceSlot(void);
extern void Ov245_FinishEnter2(void);

void Ov245_Carrier_AiDispatchAction(int self) {
    int *ctx;

    ctx = *(int **)(self + 4);
    if (*(signed char *)(ctx[0] + 0x1c7) == -1) {
        return;
    }

    *(signed char *)(ctx[0] + 0x1c6) = *(signed char *)(ctx[0] + 0x1c7);
    ((Hw60 *)(ctx[0] + 0x60))->hi &= ~0xc0;
    *(unsigned short *)(ctx[0] + 0x1ae) &= ~3;
    ((B8 *)(*(int *)(ctx[0] + 0x388) + 8))->f |= 1;

    switch (*(signed char *)(ctx[0] + 0x1c6)) {
    case 0:
        SetIndexedSlot(self, 1, Ov245_stateSetFlagsClearBit_2);
        break;
    case 1:
        SetIndexedSlot(self, 1, Ov245_StunTick);
        break;
    case 2:
        SetIndexedSlot(self, 1, Ov245_StartHoverWait);
        break;
    case 4:
        SetIndexedSlot(self, 1, Ov245_Carrier_AiEnterCharge);
        break;
    case 5:
        SetIndexedSlot(self, 1, Ov245_SetPose3ThenAdvanceSlot);
        break;
    case 3:
        SetIndexedSlot(self, 1, Ov245_FinishEnter2);
        break;
    }

    *(signed char *)(ctx[0] + 0x1c7) = -1;
}
