/* Script-VM command handler: pull this command's operands out of the descriptor
 * array through the VM's typed fetchers, build a parameter block on the stack,
 * hand it to the overlay's builder, and post the result to
 * Ov002_SetModuleSlot. Always reports success.
 *
 * Generated by tools/gen_vm_emit.py, which reads the shape straight off the
 * disassembly -- 19 functions share this skeleton and differ only in which
 * fetcher serves each slot, the descriptor offsets, and whether a slot is a word
 * or a byte.
 *
 * Two things the generator had to get right, both of which cost bytes when
 * wrong:
 *   - `adds r4, #N` advances the descriptor BASE and it STAYS advanced, so the
 *     last fetch reads descs+N, not descs.
 *   - the builder id is kept as a full word and truncated AT THE USE. Declaring
 *     it `unsigned short` truncates at the assignment instead and reorders two
 *     instructions on every member that fetches the id early.
 */
typedef struct {
    int nField00;            /* +0x00 */
    unsigned char bField04;   /* +0x04 */
    char pad05[3];
    int nField08;            /* +0x08 */
    unsigned char bField0c;   /* +0x0c */
    char pad0d[3];
    int nField10;            /* +0x10 */
    int nField14;            /* +0x14 */
    int nField18;            /* +0x18 */
} Ov002EmitParams;          /* 0x1c */

extern int ByteCode_ResolveOperand(void *self, void *desc);
extern int ScriptVm_ReadOperandInt(void *self, void *desc);
extern int ScriptVm_ReadOperandFx32(void *self, void *desc);
extern int Ov002_CreatePieceClass_2(unsigned short id, Ov002EmitParams *params);
extern void Ov002_SetModuleSlot(int target, int value);

int Ov002_VmCmd7d334(void *self, char *descs) {
    Ov002EmitParams params;
    int target;
    int id;

    params.bField04 = ScriptVm_ReadOperandInt(self, descs + 0x18);
    params.nField00 = ScriptVm_ReadOperandInt(self, descs + 0x20);
    params.nField08 = ByteCode_ResolveOperand(self, descs + 0x10);
    params.bField0c = ScriptVm_ReadOperandInt(self, descs + 0x28);
    params.nField10 = ScriptVm_ReadOperandFx32(self, descs + 0x30);
    params.nField14 = ScriptVm_ReadOperandFx32(self, descs + 0x38);
    params.nField18 = ScriptVm_ReadOperandFx32(self, descs + 0x40);
    target = ScriptVm_ReadOperandInt(self, descs);
    id = ScriptVm_ReadOperandInt(self, descs + 0x8);
    Ov002_SetModuleSlot(target, Ov002_CreatePieceClass_2((unsigned short)id, &params));
    return 1;
}
