/* Ov159_AiDispatchAction -- ov159's move dispatcher. The plain family shape: -1 at ctx[0]+0x1c7 means
 * nothing queued, the id is copied to +0x1c6 and it is that copy the switch reads, and the slot is
 * cleared on every path.
 *
 * Source case order: 0, 1, 2, 4, 5, 6, 7, 3, 8.
 * That is the body order, and it is what the switch has to say.
 *
 * Generated by tools/genmove.py from the machine code and verified byte-exact. */

typedef struct {
    unsigned short lo : 8;
    unsigned short hi : 8;
} Hw60;

typedef struct {
    unsigned f : 8;
} B8;

extern void SetIndexedSlot(int self, int slot, void (*cb)(void));
extern void Ov159_stateSetFlagsClearBit(void);
extern void Ov159_SpawnEffect48ReconfigureFlags(void);
extern void Ov159_AiEnterReach(void);
extern void Ov159_AimAtTargetAndDispatch(void);
extern void Ov159_AiEnterTurnToTarget(void);
extern void Ov159_AiEnterApproach(void);
extern void Ov159_Reaction_AimAtTargetAndDispatch(void);
extern void Ov159_SpawnEffect4aReconfigureFlagsB(void);
extern void Ov159_SpawnEffectReconfigureFlags(void);

void Ov159_AiDispatchAction(int self) {
    int *ctx;

    ctx = *(int **)(self + 4);
    if (*(signed char *)(ctx[0] + 0x1c7) != -1) {
        *(signed char *)(ctx[0] + 0x1c6) = *(signed char *)(ctx[0] + 0x1c7);
        ((Hw60 *)(ctx[0] + 0x60))->hi &= ~0xce;
        *(unsigned short *)(ctx[0] + 0x1ae) &= ~9;
        ((B8 *)(*(int *)(ctx[0] + 0x388) + 8))->f |= 1;

        switch (*(signed char *)(ctx[0] + 0x1c6)) {
        case 0:
            SetIndexedSlot(self, 1, Ov159_stateSetFlagsClearBit);
            break;
        case 1:
            SetIndexedSlot(self, 1, Ov159_SpawnEffect48ReconfigureFlags);
            break;
        case 2:
            SetIndexedSlot(self, 1, Ov159_AiEnterReach);
            break;
        case 4:
            SetIndexedSlot(self, 1, Ov159_AimAtTargetAndDispatch);
            break;
        case 5:
            SetIndexedSlot(self, 1, Ov159_AiEnterTurnToTarget);
            break;
        case 6:
            SetIndexedSlot(self, 1, Ov159_AiEnterApproach);
            break;
        case 7:
            SetIndexedSlot(self, 1, Ov159_Reaction_AimAtTargetAndDispatch);
            break;
        case 3:
            SetIndexedSlot(self, 1, Ov159_SpawnEffect4aReconfigureFlagsB);
            break;
        case 8:
            SetIndexedSlot(self, 1, Ov159_SpawnEffectReconfigureFlags);
            break;
        }
    }

    *(signed char *)(ctx[0] + 0x1c7) = -1;
}
