/* Ov138_AiDispatchAction -- ov138's move dispatcher. The plain family shape: -1 at ctx[0]+0x1c7 means
 * nothing queued, the id is copied to +0x1c6 and it is that copy the switch reads, and the slot is
 * cleared on every path.
 *
 * The "nothing queued" case RETURNS outright (a predicated `popeq`).
 *
 * Source case order: 0, 1, 2, 4, 5, 6, 7, 3, 8.
 * That is the body order, and it is what the switch has to say.
 *
 * Generated by tools/genmove.py from the machine code and verified byte-exact. */

typedef struct {
    unsigned short lo : 8;
    unsigned short hi : 8;
} Hw60;

typedef struct {
    unsigned f : 8;
} B8;

extern void SetIndexedSlot(int self, int slot, void (*cb)(void));
extern void Ov138_SetHwFlagsAndDispatch(void);
extern void Ov138_SpawnEffect48ReconfigureFlags(void);
extern void Ov138_AiEnterReach(void);
extern void Ov138_AimAtTargetAndDispatch(void);
extern void Ov138_AiEnterTurnToTarget(void);
extern void Ov138_FaceTargetSetTurnRate(void);
extern void Ov138_Reaction_AimAtTargetAndDispatch(void);
extern void Ov138_SpawnEffect4aReconfigureFlagsB(void);
extern void Ov138_EnterReturn(void);

void Ov138_AiDispatchAction(int self) {
    int *ctx;

    ctx = *(int **)(self + 4);
    if (*(signed char *)(ctx[0] + 0x1c7) == -1) {
        return;
    }

    ((Hw60 *)(ctx[0] + 0x60))->hi &= ~0xce;
    *(unsigned short *)(ctx[0] + 0x1ae) &= ~9;
    ((B8 *)(*(int *)(ctx[0] + 0x384) + 8))->f |= 1;
    *(unsigned short *)(ctx[0] + 0x1b0) = *(unsigned char *)((char *)ctx + 0x56);
    *(signed char *)(ctx[0] + 0x1c6) = *(signed char *)(ctx[0] + 0x1c7);

    switch (*(signed char *)(ctx[0] + 0x1c6)) {
    case 0:
        SetIndexedSlot(self, 1, Ov138_SetHwFlagsAndDispatch);
        break;
    case 1:
        SetIndexedSlot(self, 1, Ov138_SpawnEffect48ReconfigureFlags);
        break;
    case 2:
        SetIndexedSlot(self, 1, Ov138_AiEnterReach);
        break;
    case 4:
        SetIndexedSlot(self, 1, Ov138_AimAtTargetAndDispatch);
        break;
    case 5:
        SetIndexedSlot(self, 1, Ov138_AiEnterTurnToTarget);
        break;
    case 6:
        SetIndexedSlot(self, 1, Ov138_FaceTargetSetTurnRate);
        break;
    case 7:
        SetIndexedSlot(self, 1, Ov138_Reaction_AimAtTargetAndDispatch);
        break;
    case 3:
        SetIndexedSlot(self, 1, Ov138_SpawnEffect4aReconfigureFlagsB);
        break;
    case 8:
        SetIndexedSlot(self, 1, Ov138_EnterReturn);
        break;
    }

    *(signed char *)(ctx[0] + 0x1c7) = -1;
}
