/* Ov126_AiDispatchAction -- ov126's move dispatcher. The plain family shape: -1 at ctx[0]+0x1c7 means
 * nothing queued, the id is copied to +0x1c6 and it is that copy the switch reads, and the slot is
 * cleared on every path.
 *
 * Source case order: 0, 1, 2, 8, 3, 4, 5, 6, 7, 9.
 * That is the body order, and it is what the switch has to say.
 *
 * Generated by tools/genmove.py from the machine code and verified byte-exact. */

typedef struct {
    unsigned short lo : 8;
    unsigned short hi : 8;
} Hw60;

typedef struct {
    unsigned f : 8;
} B8;

extern void SetIndexedSlot(int self, int slot, void (*cb)(void));
extern void Ov126_stateSetFlagsClearBit(void);
extern void Ov126_ConfigHw60Action48ThenAdvance(void);
extern void Ov126_AiEnterIdle(void);
extern void Ov126_EnterAimedAttack(void);
extern void Ov126_SpawnEffect4aReconfigureFlags(void);
extern void Ov126_SetPoseThenAdvanceSlot(void);
extern void Ov126_AiEnterStrafe(void);
extern void Ov126_AiEnterSwing(void);
extern void Ov126_EnterHop(void);
extern void Ov126_EnterCharge(void);

void Ov126_AiDispatchAction(int self) {
    int *ctx;
    unsigned short v;

    ctx = *(int **)(self + 4);
    if (*(signed char *)(ctx[0] + 0x1c7) != -1) {
        v = *(unsigned short *)(ctx[0] + 0x60);
        *(unsigned short *)(ctx[0] + 0x60) =
            (unsigned short)((v & ~0xff00)
                             | (((((unsigned int)v << 0x10) >> 0x18 | 0x40) << 0x18) >> 0x10));
        ((Hw60 *)(ctx[0] + 0x60))->hi &= ~0x86;
        *(unsigned short *)(ctx[0] + 0x1ae) &= ~9;
        ((B8 *)(*(int *)(ctx[0] + 0x388) + 8))->f |= 1;
        *(signed char *)(ctx[0] + 0x1c6) = *(signed char *)(ctx[0] + 0x1c7);

        switch (*(signed char *)(ctx[0] + 0x1c6)) {
        case 0:
            SetIndexedSlot(self, 1, Ov126_stateSetFlagsClearBit);
            break;
        case 1:
            SetIndexedSlot(self, 1, Ov126_ConfigHw60Action48ThenAdvance);
            break;
        case 2:
            SetIndexedSlot(self, 1, Ov126_AiEnterIdle);
            break;
        case 8:
            SetIndexedSlot(self, 1, Ov126_EnterAimedAttack);
            break;
        case 3:
            SetIndexedSlot(self, 1, Ov126_SpawnEffect4aReconfigureFlags);
            break;
        case 4:
            SetIndexedSlot(self, 1, Ov126_SetPoseThenAdvanceSlot);
            break;
        case 5:
            SetIndexedSlot(self, 1, Ov126_AiEnterStrafe);
            break;
        case 6:
            SetIndexedSlot(self, 1, Ov126_AiEnterSwing);
            break;
        case 7:
            SetIndexedSlot(self, 1, Ov126_EnterHop);
            break;
        case 9:
            SetIndexedSlot(self, 1, Ov126_EnterCharge);
            break;
        }
    }

    *(signed char *)(ctx[0] + 0x1c7) = -1;
}
