/* Script-VM command handler: pull this command's operands out of the descriptor
 * array through the VM's typed fetchers, build a parameter block on the stack,
 * hand it to the overlay's builder, and post the result to
 * Ov002_SetModuleSlot. Always reports success.
 *
 * Generated by tools/gen_vm_emit.py, which reads the shape straight off the
 * disassembly -- 19 functions share this skeleton and differ only in which
 * fetcher serves each slot, the descriptor offsets, and whether a slot is a word
 * or a byte.
 *
 * Two things the generator had to get right, both of which cost bytes when
 * wrong:
 *   - `adds r4, #N` advances the descriptor BASE and it STAYS advanced, so the
 *     last fetch reads descs+N, not descs.
 *   - the builder's entry count is kept as a full word and truncated AT THE USE. Declaring
 *     it `unsigned short` truncates at the assignment instead and reorders two
 *     instructions on every member that fetches the count early.
 */

#include "game/engine.h"

typedef struct {
    int nField00;            /* +0x00 */
    int nField04;            /* +0x04 */
    unsigned char bField08;   /* +0x08 */
    char pad09[3];
    int nField0c;            /* +0x0c */
    int nField10;            /* +0x10 */
    int nField14;            /* +0x14 */
    unsigned char bField18;   /* +0x18 */
    char pad19[3];
} Ov016EmitParams;          /* 0x1c */

extern int Ov016_CreateEntryClass80(int nCount, Ov016EmitParams *params);
extern void Ov002_SetModuleSlot(int target, int value);

int Ov016_VmCmdCreateEntryClass80(void *self, char *descs) {
    Ov016EmitParams params;
    int target;
    int nCount;

    params.nField00 = ByteCode_ResolveOperand(self, descs + 0x10);
    params.nField04 = ScriptVm_ReadOperandFx32(self, descs + 0x18);
    params.bField08 = ScriptVm_ReadOperandInt(self, descs + 0x20);
    params.nField0c = ScriptVm_ReadOperandFx32(self, descs + 0x28);
    params.nField10 = ScriptVm_ReadOperandFx32(self, descs + 0x30);
    params.nField14 = ScriptVm_ReadOperandFx32(self, descs + 0x38);
    params.bField18 = ScriptVm_ReadOperandInt(self, descs + 0x40);
    target = ScriptVm_ReadOperandInt(self, descs);
    nCount = ScriptVm_ReadOperandInt(self, descs + 0x8);
    Ov002_SetModuleSlot(target, Ov016_CreateEntryClass80((unsigned short)nCount, &params));
    return 1;
}
