/* Script-VM command handler (family skeleton + the three ordering rules:
 * tools/gen_vm_emit.py). Generated by that tool and verified byte-exact.
 *
 * This one is in the group that only started matching once the generator learned
 * that `strh` is a HALFWORD. It had been treating everything that was not `strb`
 * as a word, so any parameter block with 16-bit slots came out with the wrong
 * field widths and every field after them shifted -- five members of the family
 * were blocked by that single assumption.
 */
typedef struct {
    int nField00;            /* +0x00 */
    int nField04;            /* +0x04 */
    short nField08;          /* +0x08 */
    short nField0a;          /* +0x0a */
    int nField0c;            /* +0x0c */
    int nField10;            /* +0x10 */
    int nField14;            /* +0x14 */
    int nField18;            /* +0x18 */
    int nField1c;            /* +0x1c */
} Ov016EmitParams;          /* 0x20 */

extern int ByteCode_ResolveOperand(void *self, void *desc);
extern int ScriptVm_ReadOperandInt(void *self, void *desc);
extern int ScriptVm_ReadOperandFx32(void *self, void *desc);
extern int Ov016_CreateBreakableClass(int nCount, Ov016EmitParams *params);
extern void Ov002_SetModuleSlot(int target, int value);

int Ov016_VmCmd1200(void *self, char *descs) {
    Ov016EmitParams params;
    int target;
    int nCount;

    target = ScriptVm_ReadOperandInt(self, descs);
    nCount = ScriptVm_ReadOperandInt(self, descs + 0x8);
    params.nField00 = ByteCode_ResolveOperand(self, descs + 0x10);
    params.nField04 = ByteCode_ResolveOperand(self, descs + 0x18);
    params.nField08 = ScriptVm_ReadOperandInt(self, descs + 0x20);
    params.nField0a = ScriptVm_ReadOperandInt(self, descs + 0x28);
    params.nField0c = ScriptVm_ReadOperandFx32(self, descs + 0x30);
    params.nField10 = ScriptVm_ReadOperandFx32(self, descs + 0x38);
    params.nField14 = ScriptVm_ReadOperandFx32(self, descs + 0x40);
    params.nField18 = ScriptVm_ReadOperandFx32(self, descs + 0x48);
    params.nField1c = ScriptVm_ReadOperandFx32(self, descs + 0x50);
    Ov002_SetModuleSlot(target, Ov016_CreateBreakableClass((unsigned short)nCount, &params));
    return 1;
}
