/* Script-VM command handler: pull this command's operands out of the descriptor
 * array through the VM's typed fetchers, build a parameter block on the stack,
 * hand it to the overlay's builder, and post the result to
 * Ov002_SetModuleSlot. Always reports success.
 *
 * Generated by tools/gen_vm_emit.py, which reads the shape straight off the
 * disassembly -- 19 functions share this skeleton and differ only in which
 * fetcher serves each slot, the descriptor offsets, and whether a slot is a word
 * or a byte.
 *
 * Two things the generator had to get right, both of which cost bytes when
 * wrong:
 *   - `adds r4, #N` advances the descriptor BASE and it STAYS advanced, so the
 *     last fetch reads descs+N, not descs.
 *   - the builder's entry count is kept as a full word and truncated AT THE USE. Declaring
 *     it `unsigned short` truncates at the assignment instead and reorders two
 *     instructions on every member that fetches the count early.
 */
typedef struct {
    int nField00;            /* +0x00 */
    int nField04;            /* +0x04 */
    int nField08;            /* +0x08 */
} Ov016EmitParams;          /* 0xc */

extern int ByteCode_ResolveOperand(void *self, void *desc);
extern int ScriptVm_ReadOperandInt(void *self, void *desc);
extern int ScriptVm_ReadOperandFx32(void *self, void *desc);
extern int Ov016_CreateEntry(int nCount, Ov016EmitParams *params);
extern void Ov002_SetModuleSlot(int target, int value);

int Ov016_VmCmdCreateEntry(void *self, char *descs) {
    Ov016EmitParams params;
    int target;
    int nCount;

    target = ScriptVm_ReadOperandInt(self, descs);
    nCount = ScriptVm_ReadOperandInt(self, descs + 0x8);
    params.nField00 = ByteCode_ResolveOperand(self, descs + 0x10);
    params.nField04 = ScriptVm_ReadOperandFx32(self, descs + 0x18);
    params.nField08 = ScriptVm_ReadOperandFx32(self, descs + 0x20);
    Ov002_SetModuleSlot(target, Ov016_CreateEntry((unsigned short)nCount, &params));
    return 1;
}
