/* Script-VM command handler (family skeleton + the three ordering rules:
 * tools/gen_vm_emit.py). Generated by that tool and verified byte-exact.
 *
 * This one is in the group that only started matching once the generator learned
 * that `strh` is a HALFWORD. It had been treating everything that was not `strb`
 * as a word, so any parameter block with 16-bit slots came out with the wrong
 * field widths and every field after them shifted -- five members of the family
 * were blocked by that single assumption.
 */
typedef struct {
    int nField00;            /* +0x00 */
    short nField04;          /* +0x04 */
    short nField06;          /* +0x06 */
    short nField08;          /* +0x08 */
    short nField0a;          /* +0x0a */
    short nField0c;          /* +0x0c */
    unsigned char bField0e;   /* +0x0e */
    unsigned char bField0f;   /* +0x0f */
} Ov016EmitParams;          /* 0x10 */

extern int ByteCode_ResolveOperand(void *self, void *desc);
extern int ScriptVm_ReadOperandInt(void *self, void *desc);
extern int ScriptVm_ReadOperandFx32(void *self, void *desc);
extern int Ov016_CreateHazardClass(int nCount, Ov016EmitParams *params);
extern void Ov002_SetModuleSlot(int target, int value);

int Ov016_VmCmd14b0(void *self, char *descs) {
    Ov016EmitParams params;
    int target;
    int nCount;

    params.nField00 = ByteCode_ResolveOperand(self, descs + 0x10);
    params.nField04 = ScriptVm_ReadOperandInt(self, descs + 0x18);
    params.nField06 = ScriptVm_ReadOperandInt(self, descs + 0x20);
    params.nField08 = ScriptVm_ReadOperandInt(self, descs + 0x28);
    params.nField0a = ScriptVm_ReadOperandFx32(self, descs + 0x30);
    params.nField0c = ScriptVm_ReadOperandInt(self, descs + 0x38);
    params.bField0e = ScriptVm_ReadOperandInt(self, descs + 0x40);
    params.bField0f = ScriptVm_ReadOperandInt(self, descs + 0x48);
    target = ScriptVm_ReadOperandInt(self, descs);
    nCount = ScriptVm_ReadOperandInt(self, descs + 0x8);
    Ov002_SetModuleSlot(target, Ov016_CreateHazardClass((unsigned short)nCount, &params));
    return 1;
}
