/* Script-VM command handler (family skeleton + the three ordering rules:
 * tools/gen_vm_emit.py). Generated by that tool and verified byte-exact.
 *
 * This one is in the group that only started matching once the generator learned
 * that `strh` is a HALFWORD. It had been treating everything that was not `strb`
 * as a word, so any parameter block with 16-bit slots came out with the wrong
 * field widths and every field after them shifted -- five members of the family
 * were blocked by that single assumption.
 */
typedef struct {
    int nField00;            /* +0x00 */
    int nField04;            /* +0x04 */
    unsigned char bField08;   /* +0x08 */
    char pad09[1];
    short nField0a;          /* +0x0a */
    short nField0c;          /* +0x0c */
    short nField0e;          /* +0x0e */
    int nField10;            /* +0x10 */
    int nField14;            /* +0x14 */
    short nField18;          /* +0x18 */
    short nField1a;          /* +0x1a */
    short nField1c;          /* +0x1c */
    short nField1e;          /* +0x1e */
    int nField20;            /* +0x20 */
    int nField24;            /* +0x24 */
} Ov002EmitParams;          /* 0x28 */

extern int ByteCode_ResolveOperand(void *self, void *desc);
extern int ScriptVm_ReadOperandInt(void *self, void *desc);
extern int ScriptVm_ReadOperandFx32(void *self, void *desc);
extern int Ov002_CreateElementClass(unsigned short id, Ov002EmitParams *params);
extern void Ov002_SetModuleSlot(int target, int value);

int Ov002_VmCmd7d004(void *self, char *descs) {
    Ov002EmitParams params;
    int target;
    int id;

    target = ScriptVm_ReadOperandInt(self, descs);
    id = ScriptVm_ReadOperandInt(self, descs + 0x8);
    params.nField00 = ByteCode_ResolveOperand(self, descs + 0x10);
    params.nField20 = ScriptVm_ReadOperandFx32(self, descs + 0x18);
    params.nField24 = ScriptVm_ReadOperandFx32(self, descs + 0x20);
    params.nField1a = ScriptVm_ReadOperandInt(self, descs + 0x28);
    params.nField1c = ScriptVm_ReadOperandInt(self, descs + 0x30);
    params.nField1e = ScriptVm_ReadOperandInt(self, descs + 0x38);
    params.nField04 = ScriptVm_ReadOperandFx32(self, descs + 0x40);
    params.bField08 = ScriptVm_ReadOperandInt(self, descs + 0x48);
    params.nField0a = ScriptVm_ReadOperandFx32(self, descs + 0x50);
    params.nField0c = ScriptVm_ReadOperandFx32(self, descs + 0x58);
    params.nField0e = ScriptVm_ReadOperandFx32(self, descs + 0x60);
    params.nField10 = ScriptVm_ReadOperandInt(self, descs + 0x68);
    params.nField14 = ScriptVm_ReadOperandInt(self, descs + 0x70);
    params.nField18 = ScriptVm_ReadOperandInt(self, descs + 0x78);
    Ov002_SetModuleSlot(target, Ov002_CreateElementClass((unsigned short)id, &params));
    return 1;
}
